repository: dynamsoft-docs/faq
repositoryUrl: https://github.com/dynamsoft-docs/faq/blob/main
docFullPath: https://www.dynamsoft.com/faq/barcode-reader
firstLevelUrl: /faq/barcode-reader
docHomePage: /faq/
product-page-url: https://www.dynamsoft.com/faq/barcode-reader

product-name: /faq/
product-title: Dynamsoft FAQ

mobile-faq: /faq/barcode-reader/mobile
server-faq: /faq/barcode-reader/server
web-faq: /faq/barcode-reader/web
general-faq: /faq/barcode-reader/general
license-faq: /faq/barcode-reader/license

useVersionTree: true

assets: /faq/barcode-reader/assets/
edit_icon: /faq/barcode-reader/assets/img-icon/edit-icon.png
smile_icon: /faq/barcode-reader/assets/img-icon/icon-smile.png
sad_icon: /faq/barcode-reader/assets/img-icon/icon-sad.png

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: https://www.dynamsoft.com # sitemap root
baseurl: /faq/barcode-reader